name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 11.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: ^0.18.0
  
dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^6.1.2
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4

  # FIREBASE
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.4.14
  firebase_auth: ^4.3.0
  firebase_storage: ^11.6.5
  firebase_remote_config: ^4.3.13
  cloud_firestore: ^4.15.4

  # FIREBASE MESSAGING
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.1.0

  # STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.9

  # IMAGE
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  lottie: ^3.0.0

  # OTHER
  country_picker: ^2.0.24
  flutter_custom_tabs: ^1.2.1
  permission_handler: ^11.3.0
  flutter_html: ^3.0.0-beta.2
  firebase_pagination: ^3.1.0
  webview_flutter: ^4.7.0

  # SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^2.0.1
  crypto: 3.0.3
  qr_flutter: ^4.1.0 #required for in pix_flutter
  pix_flutter: ^2.2.0
  razorpay_flutter: ^1.3.6
  flutterwave_standard: ^1.0.8
  flutter_stripe: ^10.0.0
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main
      
  flutter_paystack:
    git:
      url: https://github.com/Raj-GMITS/flutter_paystack.git
      ref: master    

  # MAP
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
